# Generated by Django 5.2.12 on 2026-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerapplication',
            name='pending_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
